### PR TITLE
Use a different nuget extraction routine to extract to versioned folders

### LINKED ISSUE #4075: Paket 6.0.6 does not correctly install packages
### Description

Paket v6.0.6 seems to be sometimes unpacking packages one directory too high in the filesystem hierarchy, which results in build-time warnings from .NET.

I did not see this behaviour under any previous version of Paket up to and including v6.0.0-beta8.

### Steps to Reproduce

I wish I knew, I can't get this to repro on demand.

The steps I took when this happened twice were to take an existing repo using Paket 5.x, update it to Paket 6.0.6, and add new net5.0 build targets (the repos did not previously target net5.0, only net472, netstandard2.0, and netstandard2.1).

The Paket groups have `storage: none` defined.

### Expected behavior

Paket installs packages as done previously and as done by NuGet. There are no new build warnings in my project.

### Actual behavior

image

Errors from MSBuild:
```
warning Undefined: The folder 'C:\Users\yaakov.smith\.nuget\packages\system.reflection.typeextensions\lib' contains an invalid version.
warning Undefined: The folder 'C:\Users\yaakov.smith\.nuget\packages\system.reflection.typeextensions\ref' contains an invalid version.
warning Undefined: The folder 'C:\Users\yaakov.smith\.nuget\packages\system.reflection.typeextensions\runtimes' contains an invalid version.
```

### PR DESCRIPTION
**Pull request by baronfel**
Fixes #4075 by using nuget APIs for extraction to versioned folders directly.  I also integrated logging from nuget into our logging, but behind the verboseFn safeguards so as to not spam users.

### CODE REVIEW

**Comment by baronfel** [comment]
definitely looks like there's some amount of lock contention happening as a result of this now, based on the test failures.

**Comment by baronfel** [comment]
cool, the only failing test is the same one that's failing in #4080, so if I can figure that out then we should be good to go.

**Comment by baronfel** [comment]
@smoothdeveloper do you have any ideas what might be causing the issue in this test recently?

**Comment by smoothdeveloper** [comment]
@baronfel, no idea

https://github.com/fsprojects/Paket/blob/b2feccc8f9e49f731083d2e2bfc5f47e5328eaa8/integrationtests/Paket.IntegrationTests/FsiExtension.fs

```Failed run fsi integration tests that have deterministic output [38 s]
  Error Message:
   file: C:\projects\paket\integrationtests\scenarios\fsi-depmanager\deterministic.output\PaketWithBrokenDepsFile\plot.fsx
command: fsi --langversion:preview --compilertool:C:\projects\paket\integrationtests\Paket.IntegrationTests\..\..\src\FSharp.DependencyManager.Paket\bin\Release\netstandard2.0 C:\projects\paket\integrationtests\scenarios\fsi-depmanager\deterministic.output\PaketWithBrokenDepsFile\plot.fsx
file: C:\projects\paket\integrationtests\scenarios\fsi-depmanager\deterministic.output\PaketWithDepsCanHaveGroups\plot.fsx
command: fsi --langversion:preview --compilertool:C:\projects\paket\integrationtests\Paket.IntegrationTests\..\..\src\FSharp.DependencyManager.Paket\bin\Release\netstandard2.0 C:\projects\paket\integrationtests\scenarios\fsi-depmanager\deterministic.output\PaketWithDepsCanHaveGroups\plot.fsx
file: C:\projects\paket\integrationtests\scenarios\fsi-depmanager\deterministic.output\PaketWithLocalSources\script1.fsx
command: fsi --langversion:preview --compilertool:C:\projects\paket\integrationtests\Paket.IntegrationTests\..\..\src\FSharp.DependencyManager.Paket\bin\Release\netstandard2.0 C:\projects\paket\integrationtests\scenarios\fsi-depmanager\deterministic.output\PaketWithLocalSources\script1.fsx
file: C:\projects\paket\integrationtests\scenarios\fsi-depmanager\deterministic.output\PaketWithRemoteFile\UseGlobbing.fsx
command: fsi --langversion:preview --compilertool:C:\projects\paket\integrationtests\Paket.IntegrationTests\..\..\src\FSharp.DependencyManager.Paket\bin\Release\netstandard2.0 C:\projects\paket\integrationtests\scenarios\fsi-depmanager\deterministic.output\PaketWithRemoteFile\UseGlobbing.fsx
file: C:\projects\paket\integrationtests\scenarios\fsi-depmanager\deterministic.output\SimplePaketTest\fsharp.data.fsx
command: fsi --langversion:preview --compilertool:C:\projects\paket\integrationtests\Paket.IntegrationTests\..\..\src\FSharp.DependencyManager.Paket\bin\Release\netstandard2.0 C:\projects\paket\integrationtests\scenarios\fsi-depmanager\deterministic.output\SimplePaketTest\fsharp.data.fsx
file: C:\projects\paket\integrationtests\scenarios\fsi-depmanager\deterministic.output\SimplePaketTest\plot.fsx
command: fsi --langversion:preview --compilertool:C:\projects\paket\integrationtests\Paket.IntegrationTests\..\..\src\FSharp.DependencyManager.Paket\bin\Release\netstandard2.0 C:\projects\paket\integrationtests\scenarios\fsi-depmanager\deterministic.output\SimplePaketTest\plot.fsx
file: C:\projects\paket\integrationtests\scenarios\fsi-depmanager\deterministic.output\SimplePaketTestTrim\plot.fsx
command: fsi --langversion:preview --compilertool:C:\projects\paket\integrationtests\Paket.IntegrationTests\..\..\src\FSharp.DependencyManager.Paket\bin\Release\netstandard2.0 C:\projects\paket\integrationtests\scenarios\fsi-depmanager\deterministic.output\SimplePaketTestTrim\plot.fsx
file: C:\projects\paket\integrationtests\scenarios\fsi-depmanager\deterministic.output\transitiveloadscripts\b.fsx
command: fsi --langversion:preview --compilertool:C:\projects\paket\integrationtests\Paket.IntegrationTests\..\..\src\FSharp.DependencyManager.Paket\bin\Release\netstandard2.0 C:\projects\paket\integrationtests\scenarios\fsi-depmanager\deterministic.output\transitiveloadscripts\b.fsx
  Standard Output Messages:
 KO: C:\projects\paket\integrationtests\scenarios\fsi-depmanager\deterministic.output\PaketWithBrokenDepsFile\plot.fsx
 KO: C:\projects\paket\integrationtests\scenarios\fsi-depmanager\deterministic.output\PaketWithDepsCanHaveGroups\plot.fsx
 KO: C:\projects\paket\integrationtests\scenarios\fsi-depmanager\deterministic.output\PaketWithLocalSources\script1.fsx
 KO: C:\projects\paket\integrationtests\scenarios\fsi-depmanager\deterministic.output\PaketWithRemoteFile\UseGlobbing.fsx
 KO: C:\projects\paket\integrationtests\scenarios\fsi-depmanager\deterministic.output\SimplePaketTest\fsharp.data.fsx
 KO: C:\projects\paket\integrationtests\scenarios\fsi-depmanager\deterministic.output\SimplePaketTest\plot.fsx
 KO: C:\projects\paket\integrationtests\scenarios\fsi-depmanager\deterministic.output\SimplePaketTestTrim\plot.fsx
 KO: C:\projects\paket\integrationtests\scenarios\fsi-depmanager\deterministic.output\transitiveloadscripts\b.fsx
```
 
If you don't mind checking how it behaves locally, if it passes locally, I guess adjusting the print statement to output the expected and actual output will give us an indication on what's wrong on the integration machine.

**Comment by forki** [comment]
what's the status here?

**Comment by baronfel** [comment]
Blocked by a failing test in the FSI handler, but this same test is failing in master as well so I'm not sure it's because of these changes.
