### PR TITLE
Implement a loading script generator.

### PR DESCRIPTION
**Pull request by matthid**
See #1613. This is a new PR against the v3 branch.

As I don't know when I can continue this, here is a start for 
https://github.com/fsprojects/Paket/issues/1593
https://github.com/fsprojects/Paket/issues/677

instead of https://github.com/fsprojects/Paket/pull/702 we resolve everything our-self. I don't know when I can finish this so here is what I have for now.

I think it works for Deedle for now...

Todo:
- [x] Handle dependencies within the package
- [x] Handle Framework dependencies?
- [x] Test the code
- [x] Add Mono.Cecil to ILMerge list
- [x] Integrate in Paket or a separate project
- [x] Rebase and remove "fix failing test case" commit -> https://github.com/fsprojects/Paket/pull/1644
- [x] Create documentation for this
- [ ] Create Issue/PR/Feature-Request for top level include scripts (for a group)
- [ ] Create Issue/PR/Feature-Request for generating include scripts on restore

### CODE REVIEW

**Comment by matthid** [comment]
@smoothdeveloper I rebased against the latest v3 branch and created a new `generate_scripts_v3 branch`.

**Comment by matthid** [comment]
Ok I did another round of changes. I think this is now more or less feature complete (at least how I imagined it).
As a small bonus I added a script generator for C# scripts as well. 

One minor thing are probably framework assemblies, but when this hits someone it shouldn't be too difficult to add.

@forki how should we integrate this feature?
Into paket.core and generating scripts for all defined frameworks on 'restore' (= all if user has no framework restrictions)? As a separate command? On top of paket as a separate tool (executed via FAKE)?

@smoothdeveloper Feel free to submit further changes and thank you for the help. Sorry if you have some open changes, as now you probably have a lot of merge conflicts ...

File: src/Paket.LoadingScripts/LoadingScriptsGenerator.fs [hunk 1]
```diff
@@ -225,11 +110,69 @@ module ScriptGeneratingModule =
...
+
+  let generateFSharpScript (input: ScriptGenInput) =
+    let packageName = input.PackageInstallModel.PackageName
+    let packageFolder =
+      Path.Combine (input.PackagesOrGroupFolder.FullName, packageName.GetCompareString())
+      |> DirectoryInfo
+
+    let depLines =
+      input.DependentScripts
+      |> Seq.map (fun s -> sprintf "#load \"../%s\"" (s.Replace("\\", "/")))
```
Comment (smoothdeveloper) [inline src/Paket.LoadingScripts/LoadingScriptsGenerator.fs]: I think we need a helper function given a (assembly: FileInfo) and a (packageFolder: DirectoryInfo) generate a system agnostic path.

those s.Replace here and there seems hackish.

Comment (matthid) [inline src/Paket.LoadingScripts/LoadingScriptsGenerator.fs]: Yeah and we need to escape the string properly as well. This whole thing is a bit hacky atm :)

File: src/Paket.LoadingScripts/LoadingScriptsGenerator.fs [hunk 2]
```diff
@@ -225,11 +110,69 @@ module ScriptGeneratingModule =
...
+    let dllLines =
+      dllFiles
+      |> Seq.map (fun dll -> sprintf "#r \"%s\"" (dll.Replace("\\", "/")))
+
+    depLines
+    |> fun lines -> Seq.append lines dllLines
+    |> fun lines -> Seq.append lines [ sprintf "printfn \"%%s\" \"Loaded %s\"" (packageName.GetCompareString()) ]
+
+  let generateFSharpScriptsForRootFolder =
+    let getScriptName (framework: FrameworkIdentifier) (package: PackageName) = sprintf "Include_%s_%s.fsx" (package.GetCompareString()) (framework.ToString())
```
Comment (smoothdeveloper) [inline src/Paket.LoadingScripts/LoadingScriptsGenerator.fs]: most of paket related files are all lowercase (significant for linux I guess)

I really think we should have something like this:

packages/include-scripts/{platform}/include.PackageName.fsx

package name identical to the actual nuget package identifier so might contains upper case characters, but maybe lower case that one too?

Comment (matthid) [inline src/Paket.LoadingScripts/LoadingScriptsGenerator.fs]: What if a package is named `include-scripts`? Otherwise I agree that this is probably the way to go.

File: tests/Paket.LoadingScripts.Tests/Script.fsx [hunk 3]
```diff
@@ -0,0 +1,8 @@
+﻿// Learn more about F# at http://fsharp.org. See the 'F# Tutorial' project
+// for more guidance on F# programming.
+
+#load "Library1.fs"
```
Comment (smoothdeveloper) [inline tests/Paket.LoadingScripts.Tests/Script.fsx]: let's remove that script

File: tests/Paket.LoadingScripts.Tests/LoadingScriptTests.fs [hunk 4]
```diff
@@ -0,0 +1,43 @@
+﻿module Paket.LoadingScriptTests
```
Comment (smoothdeveloper) [inline tests/Paket.LoadingScripts.Tests/LoadingScriptTests.fs]: Ok, good initiative, I think we need few integration tests with sample paket.dependencies and checking generated scripts are in place / matching expectation.

**Comment by smoothdeveloper** [comment]
@matthid: thanks for pushing :)

Seems you got rid of QuickGraph and figured out a way with just Mono.Cecil, sounds great.

I'm not sure we want scripts generated on `paket restore`, seems nice but not all users want include scripts (do they?).

I'm also not sure about the location and naming of scripts, the code should also be more resilient to such adjustments, also maybe it is better to give end user option for alternative location for the scripts to be generated?.

@forki: is it ok to add Mono.Cecil (274kb)?

File: src/Paket.LoadingScripts/LoadingScriptsGenerator.fs (hunk 2 above)
Comment (smoothdeveloper) [inline src/Paket.LoadingScripts/LoadingScriptsGenerator.fs]: We have same issue with package named same as a group.

Maybe we should put that under paket-files then?

File: src/Paket.LoadingScripts/LoadingScriptsGenerator.fs (hunk 1 above)
Comment (smoothdeveloper) [inline src/Paket.LoadingScripts/LoadingScriptsGenerator.fs]: I'll give it a spin, trying to not expand too much the code (you did a good slimming of things which ended not being useful from my changes).

**Comment by smoothdeveloper** [comment]
@matthid, we might need to deal with native binaries also, one example I found is SkiaSharp nuget package has native dll file under build/x86 and build/x64, in F# either of those directories should be included with `#I` directive.

I'm not sure yet if paket handle those files properly in terms of putting such a dependency in `paket.references` but I assume it does.

**Comment by matthid** [comment]
> we might need to deal with native binaries 

I have no idea. But it is likely that (if paket can handle those binaries) we can re-use something from the `InstallModel` class to get the required infos. If not I would say it's a paket limitation and nothing we need to figure out as part of this PR?

**Comment by smoothdeveloper** [comment]
I'm getting on top of changes right now, will update the PR shortly today.

**Comment by smoothdeveloper** [comment]
@matthid, I've made a bunch of changes, please check it out, I think it looks great.

I've tried it out on few repositories using paket and it seems to be doing great for a first take at this :smile:

**Comment by smoothdeveloper** [comment]
image

**Comment by smoothdeveloper** [comment]
@matthid I think we need to to work on those points:

* ponder on the case where no assembly nor dependent script is going to land in the script (see include.fsharp.core.fsx)
* figure out the exception when we run the code on Paket working copy itself and find a way to recover from it to generate what can be generated
* handle the error cases because packages, files are not restored, existing

@forki how do you forsee integrating this into the main tool (we need only mono.cecil now)

**Comment by forki** [comment]
Currently I'm focused on other stuff but I don't mind to depend on Cecil.
(tbh I had another use case in mind that would also depend on Cecil, but no
time for that right now)

File: src/Paket.LoadingScripts/LoadingScriptsGenerator.fs [hunk 5]
```diff
@@ -0,0 +1,219 @@
...
+        Path.Combine(rootFolder.FullName, Constants.PackagesFolderName)
+        |> DirectoryInfo
+
+      dependencies
+      |> Map.map (fun groupName packages ->
+        let packagesOrGroupFolder =
+          
+          // note: we should probably find/use Paket way to resolve package group folder
+          match groupName.GetCompareString () with
+          | "main"    -> packagesFolder
```
Comment (matthid) [inline src/Paket.LoadingScripts/LoadingScriptsGenerator.fs]: should we replace this with the constant as well?

**Comment by matthid** [comment]
> the case where no assembly nor dependent script is going to land in the script (see include.fsharp.core.fsx)

I see this more like cosmetics, can be fixed later if people have problems with it. Removing would complicate some things at this point.

> errors / exception

If we cannot create one script we cannot really create any scripts that depend on it... or we just keep going.

We should just let it fail and write the raw problem to the output (and continue whatever paket was doing). People will complain and we can fix issues as they pop up.

Or did you mean something else?

**Comment by matthid** [comment]
By the way a good set of changes, thanks. You really like the System.IO classes ;) I somehow never find them usable, but thats probably just me :)

**Comment by smoothdeveloper** [comment]
@forki 

> I don't mind to depend on Cecil.

Awesome :smile: 

@matthid 

>  It doesn't feel 'right' that the generator has to call the installmodel. Instead this type should contain all the results (for example the list of references instead of the installmodel). What do you think?

yes the overall structure didn't feel natural before I did last change, and I don't think I improved it much, we should work on making the code feel nice and simple.

Maybe we also need some integration testing, not clear yet but I'll give a look at how we can do that in current set of integration tests which have great infrastructure.

> I see this more like cosmetics, can be fixed later if people have problems with it. Removing would complicate some things at this point.

Good point

> If we cannot create one script we cannot really create any scripts that depend on it... or we just keep going.

We should generate other scripts in other branches of the dependency tree, not sure how easy that is but sounds achievable and useful.

> We should just let it fail and write the raw problem to the output (and continue whatever paket was doing). People will complain and we can fix issues as they pop up.

Yes we need to see what happens from user perspective.

Also, what do we intend end user to do?

> You really like the System.IO classes

They just make things a bit more obvious, otherwise I always wonder is this a folder, a file, etc. They incur a bit of noise (`.FullName`) but also reduce it (get name, get parent, etc.), better guarantees IMHO.

**Comment by smoothdeveloper** [comment]
@matthid, I've restored better integration points to pass higher order function for:
* custom script generators 
* script file location resolution.

I'm thinking of tackling writing some crude test, and in order to do so, leverage some of the existing integration test cases.

I'll add a ScriptGenerationTests module in the integration tests project and see how it goes.

**Comment by baronfel** [comment]
Some points came up on slack:

It would be great to have a `paket.dependencies` flag to enable script generation. something like `generate_scripts: on` that could be placed at a global, group, or individual package level, like all the other options.

Also, has there been any consideration to restoring/generating the scripts on `paket restore`? The use case I'm thinking of is a build server/CI/FAKE script flow where

- ci Server clones repo
- ci server calls build(.bat/.ps1/sh)
- ci server invokes FAKE with script
- FAKE script `#load` script includes.

This isn't a deal-breaker, because it's easy enough to have the bat/ps1/s script call the generate-scripts functionality, but it may be nice.

**Comment by baronfel** [comment]
My biggest concern with the `generate_scripts` in the dependencies file is that implies the options state being added to the lockfile, and I'm not sure that we're in the habit of adding non-dependencies-related information to the lockfile.  I could be persuaded to drop that whole line of investigation :smiley:

**Comment by matthid** [comment]
@smoothdeveloper Yes that all sounds great. I might be able to take a closer look, handle framework dependencies and write some tests on the weekend :) 

@baronfel good idea with the paket.dependencies configuration. And I agree if we include this in paket we should probably generate the scripts on restore.

**Comment by baronfel** [comment]
@matthid I've done work in the dependencies and lock file parsers before.  If you decide to go that route I'd be glad to tackle that if you're busy doing other things.

**Comment by matthid** [comment]
@baronfel good point. well we didn't do any integration at this point. because nothing felt really clean ... any suggestion/concern is welcome

**Comment by smoothdeveloper** [comment]
@matthid I think the code should now go right into Paket.Core, could you make that happen so I'm not stomping on files being moved?

Once this is done I intend to look at adding a `generate-include-scripts` command line to `paket.exe` and do some work on integration tests.

**Comment by smoothdeveloper** [comment]
@matthid I've added `generate-include-scripts` command in main executable, right now it should only be called if packages are already installed, I think we need some error handling otherwise and I'll be checking for similar checks in other commands.

@forki there is some crude framework detection going on in the code I've added, I think to keep in in this command only for now as it is very rough, but would appreciate if there is any pointer in paket codebase dealing with those aspects.

File: src/Paket.Core/ScriptGeneration.fs [hunk 6]
```diff
@@ -59,70 +59,72 @@ module PackageAndAssemblyResolution =
...
-      PackageInstallModel      : InstallModel
-      DependentScripts         : FileInfo seq
+  type ScriptGenInput = {
+      PackageName                  : PackageName
+      Framework                    : FrameworkIdentifier
+      PackagesOrGroupFolder        : DirectoryInfo
+      IncludeScriptsRootFolder     : DirectoryInfo
+      DependentScripts             : FileInfo seq
+      FrameworkReferences          : string seq
+      OrderedRealtiveDllReferences : string seq
```
Comment (smoothdeveloper) [inline src/Paket.Core/ScriptGeneration.fs]: typo? OrderedRelativeDllReferences

Comment (matthid) [inline src/Paket.Core/ScriptGeneration.fs]: yep, thanks

**Comment by matthid** [comment]
@smoothdeveloper I added framework-dependencies and moved the thing to paket.core, but I guess you already saw that :) .

**Comment by smoothdeveloper** [comment]
@matthid thanks I overlooked framework dependencies, will pay a look at how it works, thanks for cleaning a bit the mess in ScriptGeneration.fs :)

File: src/Paket.Core/ScriptGeneration.fs [hunk 7]
```diff
@@ -59,70 +59,72 @@ module PackageAndAssemblyResolution =
       getDllOrder (dllFiles.Keys |> Seq.toList)
       |> List.map (fun a -> dllFiles.[a])
 
+    let getFrameworkReferencesWithinPackage (installModel :InstallModel) =
+        installModel
+        |> InstallModel.getFrameworkAssembliesLazy
```
Comment (smoothdeveloper) [inline src/Paket.Core/ScriptGeneration.fs]: I see, good idea, thanks!

**Comment by smoothdeveloper** [comment]
@baronfel wondering if you could give a shot at adding failing or passing integration tests for things you find relevant?

I've added two tests in `integrationtests\Paket.IntegrationTests\LoadingScriptGenerationTests.fs`.

**Comment by baronfel** [comment]
Sure, I've got some time this afternoon, so I'd love to take a poke around.

**Comment by baronfel** [comment]
Found an issue with generating a build script for FAKE, looking into cause/making a test right now.

Also found that we need to add Mono.Cecil to the list of ILMerged assemblies, or else merged Paket exe that is created fails to run.  I can send that fix up as a separate commit if you grant me push privileges to your branch, @matthid.

I also have implemented a syntax for choosing the type of script to create (fsx/csx).

I have added lots of doc comments on pre-existing paket types.

It seems like there may be some low-hanging fruit in terms of parallelizing the script generation.  It's not taking too long to generate them now, but if folks complain it might be cool to look into that.

**Comment by matthid** [comment]
Yep that all sounds very nice to me! Gave you all the permissions :)
The current state looks pretty cool, thank you all for the help :+1: 

Anyone an Idea why the integration tests are failing right now?

**Comment by smoothdeveloper** [comment]
seems we should wait for #1639 to be merged and rebase here adding mono.cecil to the list.

**Comment by matthid** [comment]
@baronfel @smoothdeveloper I have no Idea why but it doesn't build via `FAKE` anymore. However when building with VisualStudio it works. Might be a compiler bug? AppVeyor says it started to fail with https://github.com/fsprojects/Paket/pull/1619/commits/4fa34e2d821163a637f5a0e9c31e29d7fae824c4

      C:\projects\paket\src\Paket\Program.fs(360,27): error FS0971: Undefined value 'scriptTypesToGenerate : ScriptType list' [C:\projects\paket\src\Paket\Paket.fsproj]

But this looks bogus to me.

One more thing: IMHO when no framework is given in command-line we should just generate scripts for all frameworks (like paket adds conditional references for all frameworks when no restriction list is given). Should I try to add that?

**Comment by matthid** [comment]
The error looks very much like this: https://github.com/Microsoft/visualfsharp/pull/742.
First question is: Do we use different compilers when compiling from VisualStudio vs FAKE?
Second: Should we add the workaround from https://github.com/Microsoft/visualfsharp/issues/759#issuecomment-162243299

**Comment by matthid** [comment]
Ok nevermind: This comment (https://github.com/Microsoft/visualfsharp/issues/759#issue-120283143) says it only happens in release mode. If you switch in VisualStudio to release mode it is failing there as well :D. Funny.

**Comment by smoothdeveloper** [comment]
> One more thing: IMHO when no framework is given in command-line we should just generate scripts for all frameworks (like paket adds conditional references for all frameworks when no restriction list is given). Should I try to add that?

I was wondering what is the point of generating .fsx for platforms such as xamarinios or xamarinandroid.

This will anyways be better than generating for current runtime only (with poor detection at that).

**Comment by smoothdeveloper** [comment]
I've looked a bit at native dependencies, right now on project level `paket.references` it works through `Paket.Reference.TargetsFile`.

Since it is msbuild stuff and we can't reasonably parse the .targets on our own to figure how to add reference, I think it would be a good idea to output maybe a warning saying that the folder with native dependency should be `#I` manually before including this dependency.

Should I make an attempt at that (for .fsx only, I think .csx doesn't support `#I`)

**Comment by matthid** [comment]
> I was wondering what is the point of generating .fsx for platforms such as xamarinios or xamarinandroid.

An app might use that some day :). You are right of course. On the other side the include scripts are quite small so they shouldn't be so much overhead even when we generate them for all platforms (you can always specify your platforms to restrict the list if you don't want all).

One point is of course if at least one package doesn't really support a given platform. But I'm not sure if we can detect this case easily... Generating only for the platforms which are supported by all the packages in the group might be preferable....

**Comment by smoothdeveloper** [comment]
> One point is of course if at least one package doesn't really support a given platform. But I'm not sure if we can detect this case easily... Generating only for the platforms which are supported by all the packages in the group might be preferable....

In Nuspec.fs there is FrameworkAssemblyReference which has FrameworkRestrictions member. I think there might be a way to not generate the script, we could also see the number of dll files to be added but that implies checking the whole reference graph for given package before generating any script.

It would still be a good idea to print something else than "Loaded package" when there is no assembly loaded.

**Comment by baronfel** [comment]
Found out my issue with FAKE's script file generation:  FAKE bundles its library in a targetframework-independent way.  it only has one version of every dependency it takes on, and they are all bundled in the tools directory.

So when we go to generate the list of dll/reference includes for the given framework, the install model for that package has no library folders and no framework references, because they are all bundled in the tools directory.

File: src/Paket.Core/ScriptGeneration.fs [hunk 8]
```diff
@@ -121,10 +123,11 @@ module ScriptGeneration =
       input.OrderedRelativeDllReferences
       |> Seq.map (sprintf """#r "%s" """)
 
-    depLines
-    |> fun lines -> Seq.append lines framworkRefLines
-    |> fun lines -> Seq.append lines dllLines
-    |> fun lines -> Seq.append lines [ sprintf "System.Console.WriteLine(\"Loaded {0}\", \"%s\");" packageName ]
+    let lines = Seq.concat [depLines; framworkRefLines; dllLines]
+
+    if Seq.isEmpty lines
```
Comment (matthid) [inline src/Paket.Core/ScriptGeneration.fs]: Maybe we should change the type of the ScriptGenInput fields to `string list` instead of `string seq` to make it more obvious to the reader that it doesn't matter that we enumerate the sequence multiple times.

Comment (smoothdeveloper) [inline src/Paket.Core/ScriptGeneration.fs]: Good point, although I'm wondering if a proper record or DU return type wouldn't be better.

```fsharp
type GeneratedScript =
| DoNotGenerate
| Generate of (lines: string list)
```

would provide a clearer message at call site and future script gen implementations.

Comment (baronfel) [inline src/Paket.Core/ScriptGeneration.fs]: Can do on both counts, updated implementation on the way

**Comment by smoothdeveloper** [comment]
I've looked more into the InstallModel and getting info about `.targets` but it seems that `Dependencies.GetInstalledPackageModel` is returning empty information in a hardcoded fashion, and getting the accurate InstallModel requires more work.

I'll leave that for future investigation in separate PR when this feature lands in v3.

Last commits look good!

File: src/Paket/Paket.fsproj [hunk 9]
```diff
@@ -99,8 +99,8 @@
     <StartArguments>update</StartArguments>
     <StartWorkingDirectory>D:\code\Paket\integrationtests\scenarios\i000346-aliases\temp</StartWorkingDirectory>
     <StartWorkingDirectory>D:\code\Paket\integrationtests\scenarios\i001585-websharper-props\temp</StartWorkingDirectory>
-    <StartArguments>pack output . include-referenced-projects minimum-from-lock-file</StartArguments>
-    <StartWorkingDirectory>D:\code\Paket\integrationtests\scenarios\i001586-pack-referenced\temp</StartWorkingDirectory>
+    <StartArguments>generate-include-scripts -v</StartArguments>
```
Comment (smoothdeveloper) [inline src/Paket/Paket.fsproj]: maybe revert that one change for easier merge?

File: src/Paket.Core/ScriptGeneration.fs [hunk 10]
```diff
@@ -165,31 +173,27 @@ module ScriptGeneration =
...
+            PackageName                  = installModel.PackageName
+            Framework                    = framework
+            PackagesOrGroupFolder        = packagesOrGroupFolder
+            IncludeScriptsRootFolder     = includeScriptsRootFolder
+            FrameworkReferences          = getFrameworkReferencesWithinPackage installModel
+            OrderedRelativeDllReferences = dllFiles
+            DependentScripts             = dependencies
+          }
+
+          let genResult = scriptGenerator scriptInfo
```
Comment (matthid) [inline src/Paket.Core/ScriptGeneration.fs]: We could inline this into the match.

**Comment by matthid** [comment]
> Projects that are tools are perhaps a special case for this functionality that should not delay the overall feature.

Yes definitely. But if we assume "tools" is always standalone (ie without dependencies to other packages) this is definitely doable.

File: src/Paket.Core/ScriptGeneration.fs (hunk 10 above)
Comment (baronfel) [inline src/Paket.Core/ScriptGeneration.fs]: Pushed a commit that inlines it.

**Comment by smoothdeveloper** [comment]
@matthid regarding Fake, one is supposed to pull FAKE.Lib package if intend to reference it.

**Comment by matthid** [comment]
Not all packages might have that and https://www.nuget.org/packages/FAKE.Lib/ doesn't list its dependencies properly either. I'm not sure this package is actually usable for anything besides simple functionality not using any dependencies (and even that might fail for example on mono which loads assemblies more eager than .NET).

**Comment by smoothdeveloper** [comment]
You are most probably right, I think this should be a concern with FAKE project and published packages.

I don't think we should do anything WRT to the tools folder in context of generated include scripts.

**Comment by matthid** [comment]
@smoothdeveloper I tend to agree (in general).
For this PR I don't think it makes sense to touch the tools folder (but future work might, if people need this for some popular packages, for example FAKE :D ).

**Comment by smoothdeveloper** [comment]
Let's open issues on FAKE repository :)

**Comment by matthid** [comment]
> It would be great to have a paket.dependencies flag to enable script generation. something like generate_scripts: on that could be placed at a global, group, or individual package level, like all the other options.

>Also, has there been any consideration to restoring/generating the scripts on paket restore? The use case I'm thinking of is a build server/CI/FAKE script flow where

>    ci Server clones repo
    ci server calls build(.bat/.ps1/sh)
    ci server invokes FAKE with script
    FAKE script #load script includes.

> This isn't a deal-breaker, because it's easy enough to have the bat/ps1/s script call the generate-scripts functionality, but it may be nice.

Actually thinking about this again. This would be a way to "clean-up" FAKE. FAKE.exe could be a more advanced `fsi.exe` (caching & stuff) and then you would `#load` all the stuff you need. We might even go further and generate a include script for a complete paket group (for example `build`).
-> add a package and you can `open` it in FAKE immediately.

So generating the include scripts on restore might actually be a good idea (maybe opt-in).

**Comment by smoothdeveloper** [comment]
@matthid @baronfel top level script for a group is a great idea!

Although I think at this stage we are entering scope creep.

There is also garbage collection (removing files that are not necessary anymore) to take in account.

Can we postpone those features to after this PR gets merged?

**Comment by smoothdeveloper** [comment]
Also, I think this feature as it is already has a lot of value and can generate some buzz, then we can generate more buzz with each further refinement to it :)

**Comment by matthid** [comment]
> @matthid I've done work in the dependencies and lock file parsers before. If you decide to go that route I'd be glad to tackle that if you're busy doing other things.

If @baronfel still want's to do it I don't have any objections. In fact we might want this on the initial version, before people start editing all their `build.cmd`/`build.sh` files :)
That's why I brought it up again. Of course we can do it later as well.

**Comment by smoothdeveloper** [comment]
Heard, seems good if we can have the option in `packages.dependencies`, we will also need to update VisualStudio plugin once v3 becomes stable release.

File: src/Paket/Program.fs [hunk 11]
```diff
@@ -301,6 +301,76 @@ let push (results : ParseResults<_>) =
...
+    let frameworksToGenerate =
+        let targetFrameworkList = providedFrameworks |> List.choose FrameworkDetection.Extract
+        
+        if targetFrameworkList.Length <> providedFrameworks.Length then
+            // print out bogus frameworks
+            providedFrameworks
+            |> Seq.map (fun f -> f, FrameworkDetection.Extract f)
+            |> Seq.filter (snd >> Option.isNone)
+            |> Seq.iter (fst >> (traceErrorfn "framework %s was unrecognized"))
+            // not sure how we should exit instead of generating for default framework
```
Comment (smoothdeveloper) [inline src/Paket/Program.fs]: any quick idea how I could make this better and exit (which I think is preferable than current behaviour: fallback to generate all)

Comment (baronfel) [inline src/Paket/Program.fs]: maybe as long as there were some provided frameworks that we recognized, generate those and leave error messages for the remaining. 

Also if some were provided but we understood none of them, then exit instead of generating all scripts for all frameworks.

Comment (matthid) [inline src/Paket/Program.fs]: IMHO we should throw an exception if one of the parameters was not recognized (fail fast & fail early).

Comment (smoothdeveloper) [inline src/Paket/Program.fs]: Are we ok with throwing an exception with all unrecognized frameworks?

**Comment by smoothdeveloper** [comment]
@matthid when you have a chance, could you rebase this off v3 branch? I'm not sure how to proceed due to the commit which was cherry picked in origin.

**Comment by matthid** [comment]
Yep wll do later today, so please make sure you don't have any open changes until like 22:00 (UTC) / 20:00 (GMT +2)

**Comment by matthid** [comment]
Don't be confused by the shrinked commit list. I used the opportunity to squash some fixup commits.
I only did some obvious things, most of the stuff is to coupled to cleanup (or from different authors which would make tracking origin harder).

**Comment by smoothdeveloper** [comment]
@matthid thanks, your level of git foo exceeds mine many fold...

I'm not sure why it just added a merge commit of mine after pulling the branch again.

So what do you all think? I believe adding the option to `paket.dependencies` can be done separately if this PR get merged into v3, so we start getting feedback from more users?

**Comment by matthid** [comment]
well rebase means git will replay all the commits on a different head. Therefore for git all rebased commits have nothing to do with the old ones... I assume you used git pull which will do a merge which is not what we want in this situation :).

what you want to do to make the magic work is:

'git fetch matthid' // replace matthid with however my fork is called on your machine.
'git rebase -i matthid/generate_scripts_v3' 
// edit the file as explained on the bottom

after this process pull can be used the next time. Alternatively you can remove your local branch and checkout mine again:

'git branch -m backup'
'git checkout -b generate_scripts_v3 matthid/generate_scripts_v3'

of course I first need to get rid of the merge commit. Will do this tomorrow.
If you want you can try to fix it youself with

'git rebase -i fsprojects/v3'
// comment the line with the merge commit (and/or the duplicates)

**Comment by matthid** [comment]
Otherwise I agree that we should probably merge as-is (after getting rid of the merge commit I will remove the WIP)

**Comment by smoothdeveloper** [comment]
Mmh, I guess I had the assumption that `pull` was identical to `fetch` + `checkout` but I guess your explanation makes clear that it does something else (a silent merge apparently). I should always use `fetch` + `rebase`.

And before your comment I didn't even see the history was completely duplicated...

Sorry for added burden of adding the spurious merge by mistake & thanks for taking time to explain. 

I was apparently able to fix the history, I gained some git foo+ some F# foo cooperating with you on this PR!

**Comment by smoothdeveloper** [comment]
@matthid/@baronfel I think everything is in place, I'm not sure about the inscrutable errors on travis & appveyor though.

Should we ask @forki to pull this in v3?

**Comment by matthid** [comment]
Hm I thought I made them green with https://github.com/fsprojects/Paket/pull/1644. Seems like that didn't hold for too long...

**Comment by smoothdeveloper** [comment]
@matthid any way we can tell Travis/AppVeyor to try again?

**Comment by matthid** [comment]
dummy commit ;)

**Comment by smoothdeveloper** [comment]
All other PR are red BTW, I don't think there is anything we can do, @matthid should you remove [WIP]?

**Comment by forki** [comment]
I think there was an issue with .NetStandard support. It all works on my machine but breaks everything on CI. Didn't have time to look into this yet. It's a bit embarrassing....

**Comment by forki** [comment]
Do we already have docs for this?

**Comment by matthid** [comment]
Good point! Added an item above, will add something very basic once I have some time (probably weekend) ;)

File: src/Paket/Program.fs [hunk 12]
```diff
@@ -301,6 +301,83 @@ let push (results : ParseResults<_>) =
...
+    let scriptTypesToGenerate = 
+      let parsedScriptTypes = providedScriptTypes |> List.choose Paket.LoadingScripts.ScriptGeneration.ScriptType.TryCreate
+      
+      failOnMismatch providedScriptTypes parsedScriptTypes Paket.LoadingScripts.ScriptGeneration.ScriptType.TryCreate "Unrecognized Script Type(s)"
+
+      match parsedScriptTypes with
+      | [] -> [Paket.LoadingScripts.ScriptGeneration.CSharp; Paket.LoadingScripts.ScriptGeneration.FSharp]
+      | xs -> xs
+
+    let workaround() = null |> ignore
```
Comment (forki) [inline src/Paket/Program.fs]: Wtf is this? ;-)

File: tests/Paket.Tests/ScriptGeneration/LoadingScriptTests.fs [hunk 13]
```diff
@@ -0,0 +1,71 @@
...
+    match output with
+    | Generate _ -> Assert.Fail()
+    | DoNotGenerate -> ()
+
+[<Test>]
+let ``generateCSharpScript returns DoNotGenerate given empty dependency set``() =
+    let output = ScriptGeneration.generateCSharpScript scriptGenInputWithNoDendency
+
+    match output with
+    | Generate _ -> Assert.Fail()
```
Comment (forki) [inline tests/Paket.Tests/ScriptGeneration/LoadingScriptTests.fs]: Can you please add a text?

File: src/Paket/Program.fs (hunk 12 above)
Comment (smoothdeveloper) [inline src/Paket/Program.fs]: @robertpi had same question in https://github.com/fsharp/FSharp.Compiler.Service/pull/453

File: tests/Paket.Tests/ScriptGeneration/LoadingScriptTests.fs (hunk 13 above)
Comment (smoothdeveloper) [inline tests/Paket.Tests/ScriptGeneration/LoadingScriptTests.fs]: doing this now

File: src/Paket/Program.fs (hunk 12 above)
Comment (matthid) [inline src/Paket/Program.fs]: @forki :) See below on the calling side or change your VS to release mode and remove it :D.

**Comment by smoothdeveloper** [comment]
@forki / @matthid I just added documentation for the command with a sample on how to use it with `FsLab` :smile:

File: docs/content/commands/generate-include-scripts.md [hunk 14]
```diff
@@ -0,0 +1,55 @@
...
+
+It is possible to generate include scripts for all registered Nuget packages defined in paket.dependencies.
+
+    [lang=batchfile]
+    $ paket generate-include-scripts framework net45
+
+This will create .csx and .fsx scripts under `paket-files/include-scripts/net45/`, those files can now be 
+used in your scripts without having to bother with the list and order of all dependencies for given package.
+
+Note: this command only works after packages have been restored, please call `paket install` before using `paket generate-include-scripts`.
```
Comment (matthid) [inline docs/content/commands/generate-include-scripts.md]: Should we say 
```
Note: this command only works after packages have been restored, please call `paket restore` before using `paket generate-include-scripts` or `paket install` if you just changed your `paket.dependencies` file.
```
?

Comment (smoothdeveloper) [inline docs/content/commands/generate-include-scripts.md]: Just replaced with what you said, makes more sense :)

**Comment by forki** [comment]
the test errors seem to be related to this PR

**Comment by smoothdeveloper** [comment]
Mmh, I need to reproduce this case on a linux / macos machine I guess, I believe the script generation doesn't end up with same scripts on windows vs mono despite the framework is specified.

Could it be that `InstallModel` gives different results on vanilla dotnet / mono?

@matthid / @forki what do you recommend we do with this test? I don't feel it should hold the feature so I might just `Assert.Ignore` with a message about that issue.

**Comment by smoothdeveloper** [comment]
@forki, I've disabled the offending test, it won't work on linux until someone can really step through the code there.

Please check again if this can be merged now.

Thanks!

**Comment by forki** [comment]
I will test this as soon as I have working Internet connection on my pc
again. The Telekom guy is coming on Monday. Sorry for delay. Blame Deutsche
Telekom.

File: docs/content/commands/generate-include-scripts.md [hunk 15]
```diff
@@ -0,0 +1,55 @@
...
+
+It is possible to generate include scripts for all registered Nuget packages defined in paket.dependencies.
+
+    [lang=batchfile]
+    $ paket generate-include-scripts framework net45
+
+This will create .csx and .fsx scripts under `paket-files/include-scripts/net45/`, those files can now be 
+used in your scripts without having to bother with the list and order of all dependencies for given package.
+
+Note: this command only works after packages have been restored, please call `paket restore` before using `paket generate-include-scripts` or `paket install` if you just changed your `paket.dependencies` file.
```
Comment (forki) [inline docs/content/commands/generate-include-scripts.md]: can we make it call restore (in a future PR)?

Comment (smoothdeveloper) [inline docs/content/commands/generate-include-scripts.md]: You mean having the command itself call restore to remove the need from the user?

If you think that's the sensible choice, yes I can make a PR for this.

Similarly, do you have an idea about how it should interact with "garbage collection" story?

Comment (forki) [inline docs/content/commands/generate-include-scripts.md]: I think create script should do a restore.
I think gc should be extended to clean unused load scripts

**Comment by forki** [comment]
Awesome work! Thanks so much. xoxo

and now:

deploy

**Comment by forki** [comment]
image

can you please try to make the test pass on ncrunch? the path is too long...

**Comment by smoothdeveloper** [comment]
Yes I'll rename the folder with all the related tests.

**Comment by smoothdeveloper** [comment]
Any chance to tell ncrunch to work somewhere else?

**Comment by forki** [comment]
maybe, but don't know how
